import defaultBreakIdeas from './defaultBreakIdeas.js'
import defaultMicrobreakIdeas from './defaultMicrobreakIdeas.js'

export default {
  microbreakDuration: 20000,
  breakDuration: 300000,
  microbreakStrictMode: false,
  breakStrictMode: false,
  mainColor: '#478484',
  miniBreakColor: '#478484',
  transparentMode: false,
  blurredBackground: false,
  opacity: 0.9,
  longBreakAudio: 'crystal-glass',
  miniBreakAudio: 'crystal-glass',
  volume: 1,
  fullscreen: false,
  currentTimeInBreaks: false,
  ideas: true,
  allScreens: true,
  useIdeasFromSettings: false,
  silentNotifications: false,
  miniBreakStartSound: 'silence',
  longBreakStartSound: 'silence',
  themeSource: 'system',
  endBreakShortcut: 'CmdOrCtrl+X',
  breakWindowWidth: 0.85,
  breakWindowHeight: 0.85,
  breakIdeas: defaultBreakIdeas,
  microbreakIdeas: defaultMicrobreakIdeas,
  showBreaksAsRegularWindows: false,
  screen: 'primary',
  breakContentScreen: 'all',
  customPreferencesMessage: '',
  hidePreferencesFileLocation: false,
  hideStrictModePreferences: false,
  miniBreakManualFinish: false,
  longBreakManualFinish: false,
  breakHealthMode: false
}
